name: Container image retention

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  packages: write
  checks: write

jobs:
  delete-package-versions:
    name: Delete package versions older than 4 weeks
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: tenstorrent
          token: ${{ secrets.GH_TOKEN }}
          image-names: "tt-torch*ci* tt-torch*ird*"
          cut-off: 4w
          keep-n-most-recent: 5
          dry-run: false
