# This workflow automates running model tests.

name: Weekly Depth Benchmarks

on:
  schedule:
    - cron: '0 10 * * 0'  # Runs at 10:00 UTC every Sunday, 6 hours after Nightly Tests
  workflow_dispatch:  # Manual trigger


jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  docker-build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
  build:
    needs: [pre-commit, spdx, docker-build]
    uses: ./.github/workflows/run-build.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      setup-args: "--include-models"
  generate-matrix:
    needs: [build]
    uses: ./.github/workflows/generate-benchmark-matrix.yml
    secrets: inherit
  run-benchmark:
    needs: [docker-build, build, generate-matrix]
    uses: ./.github/workflows/run-depth-benchmark-tests.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      matrix-json-splits: ${{ needs.generate-matrix.outputs.matrix-json-splits}}
  generate-report:
    needs: [run-benchmark]
    if: always()
    uses: ./.github/workflows/generate-benchmark-report.yml
    secrets: inherit
