# This workflow automates running model tests.

name: Weekly Depth Benchmarks

on:
  schedule:
    - cron: '0 6 * * 0'  # Runs at 06:00 UTC every Sunday
  workflow_dispatch:  # Manual trigger


jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  docker-build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
  build:
    needs: [pre-commit, spdx, docker-build]
    uses: ./.github/workflows/run-build.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
  run-benchmark:
    needs: [docker-build, build]
    uses: ./.github/workflows/run-depth-benchmark-tests.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
  generate-report:
    needs: [run-benchmark]
    uses: ./.github/workflows/generate-benchmark-report.yml
    secrets: inherit
