name: Generate Model Reports

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  tests:
    timeout-minutes: 120
    strategy:
      fail-fast: false

    runs-on:
      - n150

    container:
      image: ghcr.io/tenstorrent/tt-torch/tt-torch-ci-ubuntu-22-04:latest
      options: --user root --device /dev/tenstorrent/0
      volumes:
        - /dev/hugepages:/dev/hugepages
        - /dev/hugepages-1G:/dev/hugepages-1G
        - /etc/udev/rules.d:/etc/udev/rules.d
        - /lib/modules:/lib/modules
        - /opt/tt_metal_infra/provisioning/provisioning_env:/opt/tt_metal_infra/provisioning/provisioning_env

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "work-dir=$(pwd)" >> "$GITHUB_OUTPUT"
        echo "build-output-dir=$(pwd)/build" >> "$GITHUB_OUTPUT"
        echo "install-output-dir=$(pwd)/install" >> "$GITHUB_OUTPUT"
        echo "test-output-dir=$(pwd)/results/models/tests/" >> "$GITHUB_OUTPUT"

    - name: Git safe dir
      run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}

    - name: Use build artifacts
      uses: actions/download-artifact@v4
      with:
        name: install-artifacts
        path: ${{ steps.strings.outputs.install-output-dir }}

    - name: 'Untar install directory'
      shell: bash
      working-directory: ${{ steps.strings.outputs.install-output-dir }}
      run: |
        tar xvf artifact.tar

    - name: make tt-metal directory
      shell: bash
      working-directory: ${{ steps.strings.outputs.install-output-dir }}
      run: mkdir -p ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir/third_party/tt-metal/src/tt-metal

    - name: copy tt-metal dirs
      shell: bash
      working-directory: ${{ steps.strings.outputs.install-output-dir }}
      run: |
        cp -r ${{ steps.strings.outputs.install-output-dir }}/tt-metal/* ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir/third_party/tt-metal/src/tt-metal

    - name: make tests directory
      shell: bash
      working-directory: ${{ steps.strings.outputs.work-dir }}
      run: mkdir -p ${{ steps.strings.outputs.work-dir }}/results/models/tests/

    - name: Use build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ${{ steps.strings.outputs.test-output-dir }}
        merge-multiple: true

    - name: Display structure of downloaded file
      working-directory: ${{ steps.strings.outputs.test-output-dir }}
      run: |
        ls -R ${{ steps.strings.outputs.test-output-dir }}

    - name: Untar tests
      shell: bash
      working-directory: ${{ steps.strings.outputs.test-output-dir }}
      run: |
        rm artifact.tar
        for a in `ls -1 *.tar`; do tar -xvf $a; rm $a; done

    - name: Run Model Tests
      shell: bash
      working-directory: ${{ steps.strings.outputs.work-dir }}
      run: |
        source env/activate
        export LD_LIBRARY_PATH="/opt/ttmlir-toolchain/lib/:${{ steps.strings.outputs.install-output-dir }}/lib:${{ steps.strings.outputs.build-output-dir }}/lib:./lib/:${LD_LIBRARY_PATH}"
        export TT_TORCH_COMPILE_DEPTH=COMPILE_OP_BY_OP
        mkdir -p ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir-build/bin/
        cp ${{ steps.strings.outputs.install-output-dir }}/lib/ttmlir-opt ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir-build/bin/
        chmod +x ${{ steps.strings.outputs.work-dir }}/third_party/tt-mlir/src/tt-mlir-build/bin/ttmlir-opt
        python results/parse_op_by_op_results.py

    - name: Upload test folder to archive
      uses: actions/upload-artifact@v4
      with:
        name: models_op_per_op.xlsx
        path: "${{ steps.strings.outputs.work-dir }}/results/models_op_per_op.xlsx"
