# This workflow automates running model tests.

name: Nightly Experimental Tests

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 04:00 UTC every day
  workflow_dispatch:  # Manual trigger

permissions:
  packages: write
  checks: write

env:
  TT_TORCH_FORCE_EXPERIMENTAL_BACKEND: 1

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  docker-build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
  build:
    needs: [pre-commit, spdx, docker-build]
    uses: ./.github/workflows/run-build.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      setup-args: "--code_coverage --include-models"

  test_op_by_op:
    needs: [docker-build, build]
    uses: ./.github/workflows/run-experimental-op-by-op-model-tests.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      docker-image-harbor: ${{ needs.docker-build.outputs.docker-image-harbor }}
  download-report:
    if: success() || failure()
    needs: test_op_by_op
    uses: ./.github/workflows/generate-model-report.yml
    secrets: inherit
  generate-ttnn-md:
    if: success() || failure()
    needs: [download-report]
    uses: ./.github/workflows/generate-ttnn-md.yml
    secrets: inherit
    with:
      spreadsheet_name: ${{ needs.download-report.outputs.spreadsheet_name }}
