name: On PR

on:
  workflow_dispatch:
    inputs:
      mlir_override:
        description: 'Git SHA of commit in tenstorrent/tt-mlir'
        required: false
        type: string
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.mlir_override }}
  cancel-in-progress: true

permissions:
  packages: write
  checks: write

jobs:
  pre-commit:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  docker-build:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      mlir_override: ${{ inputs.mlir_override }}

  build:
    needs: [pre-commit, spdx, docker-build, check-files]
    if: github.event.pull_request.draft == false && needs.check-files.outputs.skip == 'false'
    uses: ./.github/workflows/run-build.yml
    secrets: inherit
    with:
      mlir_override: ${{ github.event.inputs.mlir_override }}
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      setup-args: "--build_perf --include-models" #TODO - This should be toggleable?
  full-model-test:
    needs: [build, docker-build]
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/run-full-model-execution-tests.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      run-codecov: 'false'
      run-dump-mlir: 'false'
