name: On PR bot review
# This workflow runs on pull requests to perform static code analysis using pyflakes and cppcheck.
on: [pull_request]
jobs:
  pyflakes:
    name: Py Flake8
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify the Python version you want to use
      - name: Install dependencies
        run: python -m pip install flake8 flake8-sarif
      - name: Run Flake8
        run: |
          flake8 -vv --output-file=.output.sarif --format=sarif --ignore=E501 .
          # cat .output.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .output.sarif
          category: PyFlake8

  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        clean: true
        fetch-depth: 0 # Fetch all history and tags
    - name: Setup Cppcheck
      run: |
        sudo debconf-set man-db/auto-update false
        TEMP_DEB="$(mktemp)" && \
        wget -O "$TEMP_DEB" 'https://launchpad.net/ubuntu/+archive/primary/+files/cppcheck_2.17.1-1_amd64.deb' && \
        sudo dpkg -i "$TEMP_DEB" && \
        rm -f "$TEMP_DEB"
    - name: Run Cppcheck with reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd tt_torch/csrc
        cppcheck --std=c++17 --check-level=exhaustive --enable=warning,information --platform=unix64 --suppress=uninitMemberVar --output-file=../../.output.sarif --output-format=sarif .
        cd ../..
        cat .output.sarif
        jq '.runs[].tool.driver.rules[].properties |= (if has("security-severity") then .["security-severity"] |= tostring else . end)' .output.sarif > .output_updated.sarif
        mv .output_updated.sarif .output.sarif
        # cat .output.sarif | reviewdog -f=sarif -reporter=github-pr-review -level=warning -fail-on-error=true -filter-mode=nofilter -diff="git diff origin/main" -tee

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: .output.sarif
        category: cppcheck
