name: reviewdog
on: [pull_request]
jobs:
  pyflakes:
    name: runner / pyflakes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: pyflakes
        uses: reviewdog/action-pyflakes@2d6743a6bb878aba173c913783dd568f4f2c2743
        with:
          github_token: ${{  github.token }}
          reporter: github-pr-check

  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        clean: true
        fetch-depth: 0 # Fetch all history and tags
    - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
      with:
        reviewdog_version: latest
    - name: Setup Cppcheck
      run: |
        TEMP_DEB="$(mktemp)" && \
        wget -O "$TEMP_DEB" 'https://launchpad.net/ubuntu/+archive/primary/+files/cppcheck_2.17.1-1_amd64.deb' && \
        sudo dpkg -i "$TEMP_DEB" && \
        rm -f "$TEMP_DEB"
    - name: Run Cppcheck with reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
      run: |
        cd tt_torch/csrc
        cppcheck --std=c++17 --check-level=exhaustive --enable=warning,information --platform=unix64 --suppress=uninitMemberVar --output-file=../../.output.sarif --output-format=sarif .
        cd ../..
        cat .output.sarif | reviewdog -f=sarif -reporter=github-pr-check -level=warning -fail-on-error=true -filter-mode=nofilter -diff="git diff origin/main" -tee
