name: "[internal] Collect workflow data"
run-name: "Collect data for run_id ${{ github.event.workflow_run.id }} attempt ${{ github.event.workflow_run.run_attempt }}"

on:
  workflow_run:
    workflows: # List workflow that we want to collect data for
      - "On PR"
      - "On push"
      - "Nightly Tests"
      - "Run Model Tests"
      - "Run Tests"
      - "Nightly Experimental Tests"
    types:
      - completed
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID to collect data for'
        required: true
        default: '0'
      run_attempt:
        description: 'Run attempt to collect data for'
        required: true
        default: '1'
jobs:
  produce-cicd-data:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
      - name: Debug manual dispatch inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "=== Manual Dispatch Debug Info ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Run ID input: ${{ github.event.inputs.run_id }}"
          echo "Run attempt input: ${{ github.event.inputs.run_attempt }}"
          echo "================================="

      - name: Collect CI/CD data (from workflow_run)
        uses: tenstorrent/tt-github-actions/.github/actions/collect_data@main
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          repository: ${{ github.repository }}
          run_id: ${{ github.event.workflow_run.id }}
          run_attempt: ${{ github.event.workflow_run.run_attempt }}
          sftp_host: ${{ secrets.SFTP_CICD_WRITER_HOSTNAME }}
          sftp_user: ${{ secrets.SFTP_CICD_WRITER_USERNAME }}
          sftp_optest_host: ${{ secrets.SFTP_OP_TEST_WRITER_HOSTNAME }}
          sftp_optest_user: ${{ secrets.SFTP_OP_TEST_WRITER_USERNAME }}
          ssh-private-key: ${{ secrets.SFTP_CICD_WRITER_KEY }}

      - name: Collect CI/CD data (from manual dispatch)
        uses: tenstorrent/tt-github-actions/.github/actions/collect_data@main
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          repository: ${{ github.repository }}
          run_id: ${{ github.event.inputs.run_id }}
          run_attempt: ${{ github.event.inputs.run_attempt }}
          sftp_host: ${{ secrets.SFTP_CICD_WRITER_HOSTNAME }}
          sftp_user: ${{ secrets.SFTP_CICD_WRITER_USERNAME }}
          sftp_optest_host: ${{ secrets.SFTP_OP_TEST_WRITER_HOSTNAME }}
          sftp_optest_user: ${{ secrets.SFTP_OP_TEST_WRITER_USERNAME }}
          ssh-private-key: ${{ secrets.SFTP_CICD_WRITER_KEY }}
