name: reviewdog
on: [pull_request]
permissions:
  contents: read
jobs:
  pyflakes:
    name: runner / pyflakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pyflakes
        uses: reviewdog/action-pyflakes@2d6743a6bb878aba173c913783dd568f4f2c2743
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-check
