name: spdx

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKER_CACHE_ROOT: /mnt/dockercache
jobs:
  check-spdx-headers:


    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: enarx/spdx@master
      with:
        licenses: |-
          Apache-2.0
          MIT
    - name: test-env
      run: |
        echo "DOCKER_CACHE_ROOT=$DOCKER_CACHE_ROOT"
