name: spdx

on:
  workflow_dispatch:
  workflow_call:


# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     outputs:
#       matrix: ${{ steps.set-matrix.outputs.matrix }}
#     steps:
#       - id: set-matrix
#         run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
#   job2:
#     needs: job1
#     runs-on: ubuntu-latest
#     strategy:
#       matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
#     steps:
#       - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"


jobs:
  job0:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set matrix
        id: set-matrix
        run: echo "matrix=$(cat benchmark_test_matrix_splits.json)" >> $GITHUB_OUTPUT
      - name: ls
        run: ls -al
      - name: Upload xls report to archive
        uses: actions/upload-artifact@v4
        with:
          name: "matrix-json"
          path: "benchmark_test_matrix.json"

  job1:
    runs-on: ubuntu-latest
    needs: job0
    strategy:
      fail-fast: false
      matrix:
        group: ${{ fromJSON(needs.job0.outputs.matrix) }}
    name: ${{ matrix.group.name }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: enarx/spdx@master
      with:
        licenses: |-
          Apache-2.0
          MIT
    # can't overlap the download path with a file that already exists at the given path
    - name: Download test matrix contents
      uses: actions/download-artifact@v4
      with:
        name: "matrix-json"
        path: "test_matrix/benchmark_test_matrix.json"
    - name: dummy step
      id: dummy
      run: |
          echo "My group is ${{ matrix.group.runs-on }} with index ${{ matrix.group.group-id }}"
          cat benchmark_test_matrix.json
          # Read the JSON file and extract the i'th entry
          entry=$(cat benchmark_test_matrix.json | jq ".[${{ matrix.group.group-id }}]")
          set -e
          # Iterate over the "tests" array within the entry
          echo "$entry" | jq -c '.tests[]' | while read -r test; do
              # Extract the test name and duration
              test_name=$(echo "$test" | jq -r '.["full-test-name"]')
              test_duration=$(echo "$test" | jq -r '.["test-duration"]')

              # Apply timeout and invoke pytest
              echo "Running test: $test_name with timeout: $test_duration seconds"
              timeout "$test_duration"s pytest "$test_name"
          done
          set +e
