name: TT-Forge Model Tests Wrapper

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      reuse-build-run-id:
        description: 'Reuse build artifacts from specific run ID (skips build job)'
        required: false
        type: string
      tests-filter-passing:
        description: 'Filter for passing tests'
        required: false
        type: string
        default: "expected_passing"
      tests-filter-xfail:
        description: 'Filter for xfail tests'
        required: false
        type: string
        default: "not expected_passing"
      num-splits-passing:
        description: 'Number of splits for passing tests'
        required: false
        type: number
        default: 2
      num-splits-xfail:
        description: 'Number of splits for xfail tests'
        required: false
        type: number
        default: 1

permissions:
  packages: write
  checks: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug inputs
        run: |
          echo "=== GitHub Context ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.ref_name }}"
          echo ""
          echo "=== Input Debug ==="
          echo "reuse-build-run-id: '${{ inputs.reuse-build-run-id }}'"
          echo "Truthiness check: ${{ !!inputs.reuse-build-run-id }}"
          echo "Build job should run: ${{ !inputs.reuse-build-run-id }}"
          echo "Test jobs should run: ${{ !!inputs.reuse-build-run-id }}"
          if [ -z "${{ inputs.reuse-build-run-id }}" ]; then
            echo "Input is empty (bash test) -> BUILD will run"
          else
            echo "Input is not empty (bash test) -> BUILD will be SKIPPED"
          fi

  docker-build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
  build:
    if: ${{ !inputs.reuse-build-run-id }}  # Only run if not reusing artifacts
    needs: docker-build
    uses: ./.github/workflows/run-build.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      setup-args: "--code_coverage --include-models --build_perf"
  test-passing-tt-forge-models:
    needs: [docker-build, build]
    if: ${{ always() && (inputs.reuse-build-run-id || needs.build.result == 'success') }}
    uses: ./.github/workflows/run-tt-forge-models-tests.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      tests-filter: ${{ inputs.tests-filter-passing }}
      num-splits: ${{ fromJSON(inputs.num-splits-passing) }}
      reuse-build-run-id: ${{ inputs.reuse-build-run-id }}
  test-xfail-tt-forge-models:
    needs: [docker-build, build]
    if: ${{ always() && (inputs.reuse-build-run-id || needs.build.result == 'success') }}
    uses: ./.github/workflows/run-tt-forge-models-tests.yml
    secrets: inherit
    with:
      docker-image: ${{ needs.docker-build.outputs.docker-image }}
      tests-filter: ${{ inputs.tests-filter-xfail }}
      num-splits: ${{ fromJSON(inputs.num-splits-xfail) }}
      reuse-build-run-id: ${{ inputs.reuse-build-run-id }}
